name: NeuraLumaWhisperCPU
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - ffmpeg
  - pip:
    - jax[cpu]==0.4.11
    - git+https://github.com/sanchit-gandhi/whisper-jax.git
    - gradio==3.35.2
    - transformers==4.30.0
    - cached_property==1.5.2
    #- pytube==15.0.0
    - git+https://github.com/flywiththetide/pytube.git # Currently contains a fix for pytube regex
    - moviepy==1.0.3
    - datasets[audio]==2.13.1
    - huggingface_hub